x = input('Atribua algo a x ')
print('O tipo primitivo de x é:', type(x))
print('x é um número?', x.isnumeric())
print('x é um texto?', x.isalpha())
print('x é um alfanumérico?', x.isalnum())
print('x só tem espaços?', x.isspace())
print('x está em maiúsculas?', x.isupper())
print('x está em minúsculas?', x.islower())
print('x está capitalizado?', x.istitle())
